### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by ed1nh0** [diogocezar/dctb-crawler#1]
Fui rodar e deu tudo certo, porém no final do processo retornou esse erro tanto quanto o número de filmes:

```
(node:24212) [DEP0013] DeprecationWarning: Calling an asynchronous function with
out callback is deprecated.
```

E o arquivo gerado (.txt) não tinha quebras de linha (`\n`)

**Comment by diogocezar** [comment]
Fala man, esse é um estudo bem antigo.

Alguma sugestão de como corrigir?
